"""Add assigned_contractor_id to Job model

Revision ID: 0386be2d6c2a
Revises: a77c3dd083bc
Create Date: 2025-05-21 10:53:43.855597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0386be2d6c2a'
down_revision = 'a77c3dd083bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_contractor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_jobs_assigned_contractor_id_users', 'users', ['assigned_contractor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_assigned_contractor_id_users', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('assigned_contractor_id')

    # ### end Alembic commands ###
