"""Make from_status nullable in project_status_history

Revision ID: 2e72270274fc
Revises: 2e104d35a4a3
Create Date: 2025-05-21 22:32:41.432896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e72270274fc'
down_revision = '2e104d35a4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_status_history',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('open', 'in_progress', 'completed', 'awarded', name='job_status'), nullable=True),
    sa.Column('to_status', sa.Enum('open', 'in_progress', 'completed', 'awarded', name='job_status'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'])
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('bid_team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('idx_bid_team_members_bid_id')
        batch_op.drop_index('idx_bid_team_members_email')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('timeline_weeks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_match_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('proposed_timeline')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('professional_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_job_professional_review', ['job_id', 'professional_id'])

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('nca_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_ratings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('successful_bids', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_bids', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('business_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_logo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('business_banner', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('business_banner')
        batch_op.drop_column('business_logo')
        batch_op.drop_column('business_website')
        batch_op.drop_column('business_phone')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_description')
        batch_op.drop_column('business_name')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_active')
        batch_op.drop_column('total_bids')
        batch_op.drop_column('successful_bids')
        batch_op.drop_column('total_ratings')
        batch_op.drop_column('average_rating')
        batch_op.drop_column('nca_level')
        batch_op.drop_column('phone')
        batch_op.drop_column('password')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_job_professional_review', type_='unique')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('professional_skills', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('message')
        batch_op.drop_column('title')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_timeline', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('location_match_type')
        batch_op.drop_column('location_score')
        batch_op.drop_column('timeline_weeks')
        batch_op.drop_column('proposal')

    with op.batch_alter_table('bid_team_members', schema=None) as batch_op:
        batch_op.create_index('idx_bid_team_members_email', ['email'], unique=False)
        batch_op.create_index('idx_bid_team_members_bid_id', ['bid_id'], unique=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('filename')
        batch_op.drop_column('uploaded_by')

    op.drop_table('project_status_history')
    # ### end Alembic commands ###
